### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by robbecker-wf**
Update the copyright info to 2015 Workiva Inc.

### CODE REVIEW

**Comment by stephenbush-wf** [comment]
Looks good!

There's a few places (pretty much just documentation) where it still says WebFilings, if you care enough you could roll those in!

+1

**Comment by patkujawa-wf** [comment]
I'll do uicomp

**Comment by robbecker-wf** [comment]
Updated WebFilings to Workiva

**Comment by stephenbush-wf** [comment]
+1

**Comment by tomconnell-wf** [comment]
QA +1

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
- [ ] Unit test created/updated 
- [ ] All unit tests pass 
- [ ] Rosie has run and reports the proper release ticket

Merging into master.

**Comment by tomconnell-wf** [comment]
QA +1

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
- [ ] Unit test created/updated 
- [ ] All unit tests pass 
- [ ] Rosie has run and reports the proper release ticket

Merging into master.

**Comment by tomconnell-wf** [comment]
@rmconsole-wf

**Pull request merged**
