### PR TITLE
HY-2645 Release wf-common 1.1.1

### PR DESCRIPTION
**Pull request by tomconnell-wf**
PRs contained in this release:

https://github.com/Workiva/wf-common/pull/45

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/wf-common/compare/1.1.0...Release_1.1.1

### CODE REVIEW

**Comment by robbecker-wf** [comment]
+1

**Comment by patkujawa-wf** [comment]
+1 +semver - public API seems unchanged and this is only a bugfix

**Comment by tomconnell-wf** [comment]
Releases
Quality Review +1

- [x] Dev +1 only needed for release.

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
