### PR TITLE
HY-3494 fix tests, remove duplicate/unneeded polyfills

### PR DESCRIPTION
**Pull request by robbecker-wf**
# Problem
 - There are some flaky unit tests due to setting document.createEvent to null in specs
 - a require path uses src/Url instead of wf-js-common/Url
 - There are duplicate and unneeded polyfills

# Solution
Fix the tests and remove the unneeded code!

# Testing
 - [ ] Unit tests should all pass

### CODE REVIEW

**Comment by stephenbush-wf** [comment]
@rmconsole-wf

**Comment by stephenbush-wf** [comment]
+1

**Comment by seanburke-wf** [comment]
+10; CI passed, and manually ran `grunt test' on a local clone. Passed.

**Comment by stephenbush-wf** [comment]
Quality Review +1 ( aka QA: +1 )

- [X] Testing instruction
- [X] Dev +1's
- [X] Dev/QA +10 with detail of what was tested
- [X] Unit test created/updated 
- [X] All unit tests pass 
- [X] Rosie has run and reports the proper release ticket

Merging into master.

**Pull request merged**
