### PR TITLE
HY-2818 Release wf-common 1.1.4

### PR DESCRIPTION
**Pull request by charliekump-wf**
PRs contained in this release:

https://github.com/Workiva/wf-common/pull/52

https://github.com/Workiva/wf-common/pull/54

https://github.com/Workiva/wf-common/pull/55

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/wf-common/compare/1.1.3...Release_1.1.4

### CODE REVIEW

**Comment by seanburke-wf** [comment]
+1 +semver

**Comment by seanburke-wf** [comment]
+1 on the changes

**Comment by patkujawa-wf** [comment]
+1 as well

**Comment by patkujawa-wf** [comment]
Quality Review Approval: +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Unit test created/updated
- [x] All unit tests pass
- [ ] Rosie has run and reports properly the release the ticket will be included in

Merging into master.

**Pull request merged**
